services:
  webserver:
      image: webdevops/php-apache:7.3-alpine
      ports:
        - 80:80
        - 443:443
      volumes:
        - .:/var/www/html
      environment:
        WEB_DOCUMENT_ROOT: /var/www/html/$ROOT_FOLDER
        PHP_DATE_TIMEZONE: America/Sao_Paulo

volumes:
    data: